from __future__ import annotations

from .written_test import NO_UNIFIED_WRITTEN_TEST, REQUIRED, ASSESSMENT_ONLY

DEMO_COMPANIES = [
    {
        "name": "示例能源集团",
        "aliases": ["Demo Energy Group"],
        "company_type": "央企",
        "industry": "能源电力",
        "official_site": "https://example.com/energy",
        "recruit_site": "https://example.com/energy/campus",
        "source_level": "S",
        "campaigns": [
            {
                "name": "2027届秋招提前批",
                "recruitment_type": "提前批",
                "target_cohort": "2027届",
                "status": "open",
                "deadline": "2026-08-31",
                "domestic_grad_start": "2026-09",
                "domestic_grad_end": "2027-08",
                "overseas_grad_start": "2026-09",
                "overseas_grad_end": "2027-08",
                "accepts_overseas": True,
                "degree_min": "bachelor",
                "apply_url": "https://example.com/energy/apply",
                "source_url": "https://example.com/energy/notice-2027",
                "source_level": "S",
                "process_rule": {
                    "written_test_status": REQUIRED,
                    "written_test_burden": 4,
                    "process_text": "招聘流程包含网申、统一笔试、面试和录用。博士岗位可视情况免笔试。",
                    "confidence": 0.88,
                },
                "jobs": [
                    {
                        "title": "数字化产品经理",
                        "job_family": "产品",
                        "cities": ["北京", "上海"],
                        "degree_min": "bachelor",
                        "majors": ["计算机", "管理科学", "信息系统"],
                        "description": "负责能源数字化产品规划、需求分析和项目推进。",
                        "quality_score": 0.91,
                        "risk_level": "low",
                    },
                    {
                        "title": "电力系统工程师",
                        "job_family": "技术",
                        "cities": ["北京", "西安", "武汉"],
                        "degree_min": "master",
                        "majors": ["电气工程", "自动化"],
                        "description": "负责电力系统规划、仿真和技术支持。",
                        "quality_score": 0.89,
                        "risk_level": "low",
                    },
                ],
            }
        ],
    },
    {
        "name": "示例游戏科技",
        "aliases": ["Demo Game Tech"],
        "company_type": "民企",
        "industry": "游戏互联网",
        "official_site": "https://example.com/game",
        "recruit_site": "https://example.com/game/campus",
        "source_level": "A",
        "campaigns": [
            {
                "name": "2026届春季校园招聘",
                "recruitment_type": "春招",
                "target_cohort": "2026届",
                "status": "open",
                "deadline": "2026-07-31",
                "domestic_grad_start": "2025-09",
                "domestic_grad_end": "2026-08",
                "overseas_grad_start": "2025-09",
                "overseas_grad_end": "2026-08",
                "accepts_overseas": True,
                "degree_min": "bachelor",
                "apply_url": "https://example.com/game/apply",
                "source_url": "https://example.com/game/notice-2026-spring",
                "source_level": "A",
                "process_rule": {
                    "written_test_status": NO_UNIFIED_WRITTEN_TEST,
                    "written_test_burden": 1,
                    "process_text": "本届春招不设置统一笔试，美术设计类及个别需要笔试的职位会单独通知。",
                    "confidence": 0.86,
                },
                "jobs": [
                    {
                        "title": "游戏产品策划",
                        "job_family": "产品",
                        "cities": ["上海", "广州"],
                        "degree_min": "bachelor",
                        "majors": ["不限专业"],
                        "description": "负责游戏产品玩法设计、用户研究和版本规划。",
                        "quality_score": 0.86,
                        "risk_level": "low",
                    },
                    {
                        "title": "用户运营管培生",
                        "job_family": "运营",
                        "cities": ["上海"],
                        "degree_min": "bachelor",
                        "majors": ["不限专业"],
                        "description": "负责用户增长、活动运营和社区维护。",
                        "quality_score": 0.83,
                        "risk_level": "low",
                    },
                ],
            }
        ],
    },
    {
        "name": "示例咨询中国",
        "aliases": ["Demo Consulting China"],
        "company_type": "外企",
        "industry": "咨询",
        "official_site": "https://example.com/consulting",
        "recruit_site": "https://example.com/consulting/careers",
        "source_level": "B",
        "campaigns": [
            {
                "name": "2026海外学子招聘计划",
                "recruitment_type": "海外专场",
                "target_cohort": "2026届",
                "status": "open",
                "deadline": "2026-09-15",
                "domestic_grad_start": None,
                "domestic_grad_end": None,
                "overseas_grad_start": "2024-08",
                "overseas_grad_end": "2026-08",
                "accepts_overseas": True,
                "degree_min": "bachelor",
                "apply_url": "https://example.com/consulting/apply",
                "source_url": "https://example.com/consulting/overseas-program",
                "source_level": "B",
                "process_rule": {
                    "written_test_status": ASSESSMENT_ONLY,
                    "written_test_burden": 2,
                    "process_text": "招聘流程包含网申、在线测评、面试和 offer。未提及统一笔试。",
                    "confidence": 0.72,
                },
                "jobs": [
                    {
                        "title": "管理咨询顾问",
                        "job_family": "咨询",
                        "cities": ["北京", "上海", "深圳"],
                        "degree_min": "bachelor",
                        "majors": ["不限专业"],
                        "description": "面向海外学子，参与战略、运营和数字化转型项目。",
                        "quality_score": 0.78,
                        "risk_level": "medium",
                    }
                ],
            }
        ],
    },
]

DEMO_SIGNALS = [
    {
        "company_name": "示例能源集团",
        "signal_type": "official_site_change",
        "title": "官网出现 2027 届秋招提前批入口",
        "description": "监测到公司招聘站新增提前批入口。当前状态为演示信号。",
        "source_url": "https://example.com/energy/notice-2027",
        "source_level": "S",
        "status": "confirmed_source",
        "evidence_text": "页面标题包含 2027届秋招提前批。",
    },
    {
        "company_name": "示例游戏科技",
        "signal_type": "notice_imported",
        "title": "春招公告显示不设置统一笔试",
        "description": "公告文本提到不设置统一笔试，但个别岗位可能单独通知。",
        "source_url": "https://example.com/game/notice-2026-spring",
        "source_level": "A",
        "status": "parsed",
        "evidence_text": "本届春招不设置统一笔试，美术设计类及个别需要笔试的职位会单独通知。",
    },
]
